---
registry:
# Lock screen after 5 minutes
- key: HKLM:/SOFTWARE/Microsoft/Windows/CurrentVersion/Policies/System
  name: InactivityTimeoutSecs
  type: DWord
  value: 300
# Disable a bunch of insecure ciphers/key exchange/hashes/protocols and enable
# only those that are secure.
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/NULL
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/DES 56/56
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/RC2 40/128
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/RC2 56/128
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/RC2 128/128
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/RC4 40/128
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/RC4 56/128
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/RC4 64/128
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/RC4 128/128
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/Triple DES 168
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/AES 128/128
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Ciphers/AES 256/256
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Hashes/MD5
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Hashes/SHA
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Hashes/SHA256
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Hashes/SHA384
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Hashes/SHA512
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/KeyExchangeAlgorithms/Diffie-Hellman
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/KeyExchangeAlgorithms/PKCS
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/KeyExchangeAlgorithms/ECDH
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/Multi-Protocol Unified Hello/Client
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/PCT 1.0/Client
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 2.0/Client
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 3.0/Client
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.0/Client
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.1/Client
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.2/Client
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/Multi-Protocol Unified Hello/Client
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/PCT 1.0/Client
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 2.0/Client
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 3.0/Client
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.0/Client
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.1/Client
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.2/Client
  name: DisabledByDefault
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/Multi-Protocol Unified Hello/Server
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/PCT 1.0/Server
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 2.0/Server
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 3.0/Server
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.0/Server
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.1/Server
  name: Enabled
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.2/Server
  name: Enabled
  type: DWord
  value: 0xffffffff
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/Multi-Protocol Unified Hello/Server
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/PCT 1.0/Server
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 2.0/Server
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/SSL 3.0/Server
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.0/Server
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.1/Server
  name: DisabledByDefault
  type: DWord
  value: 1
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols/TLS 1.2/Server
  name: DisabledByDefault
  type: DWord
  value: 0
- key: HKLM:/SYSTEM/CurrentControlSet/Control/SecurityProviders/SCHANNEL/KeyExchangeAlgorithms/Diffie-Hellman
  name: ServerMinKeyBitLength
  type: DWord
  value: 0x800
- key: HKLM:/SYSTEM/CurrentControlSet/Control/Lsa/FipsAlgorithmPolicy
  name: Enabled
  type: DWord
  value: 0
