---
chocopackages:
- vscode
- cascadiafonts
- cryptsync
- git
- fiddler
- adobe-creative-cloud
- 7zip
- microsoft-teams
- powertoys
consolecolors:
- "#282c34"
- "#61afef"
- "#98c379"
- "#56b6c2"
- "#e06c75"
- "#c678dd"
- "#d19a66"
- "#abb2bf"
- "#828997"
- "#61afef"
- "#98c379"
- "#56b6c2"
- "#e5847b"
- "#c678dd"
- "#e5c07b"
- "#ffffff"
storeapps:
- Microsoft.Messaging
- Microsoft.Microsoft3DViewer
- Microsoft.MicrosoftOfficeHub
- Microsoft.MicrosoftSolitaireCollection
- Microsoft.MicrosoftStickyNotes
- Microsoft.MixedReality.Portal
  # Paint 3D
- Microsoft.MSPaint
  # Mobile Plans
- Microsoft.OneConnect
- Microsoft.People
  # Mail and Calendar
- Microsoft.WindowsCommunicationsApps
- Microsoft.WindowsMaps
  # Voice recorder
- Microsoft.WindowsSoundRecorder
- Microsoft.XboxApp
  # XBox Game Bar
- Microsoft.XboxGamingOverlay
- Microsoft.ZuneMusic
- Microsoft.ZuneVideo
  # Roblox
- RobloxCorporation.Roblox
  # Spotify
- SpotifyAB.SpotifyMusic
symlinks:
- path: AppData/Local/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe
  name: LocalState
  target: Windows Terminal Settings
psmodules:
- AzureADPreview
- Az
- ExchangeOnlineManagement
- MicrosoftTeams
- Microsoft.Online.SharePoint.PowerShell
- MSOnline
- oh-my-posh
- posh-git
registrysettings:
- key: HKCU:/Software/Policies/Microsoft/Edge
  entries:
  # Shopping assistant = off
  - name: EdgeShoppingAssistantEnabled
    type: DWord
    value: 0
  # Do not track = on
  - name: ConfigureDoNotTrack
    type: DWord
    value: 1
  # Tracking protection = strict
  - name: TrackingPrevention
    type: DWord
    value: 3
  # Password manager = disabled
  - name: PasswordManagerEnabled
    type: DWord
    value: 0
  # Import saved passwords = disabled
  - name: ImportSavedPasswords
    type: DWord
    value: 0
  # Default search provider = enabled
  - name: DefaultSearchProviderEnabled
    type: DWord
    value: 1
  - name: DefaultSearchProviderName
    type: String
    value: Google
  - name: DefaultSearchProviderKeyword
    type: String
    value: google.com
  # Default search provider image search URL
  - name: DefaultSearchProviderImageURL
    type: String
    value: "{google:baseURL}searchbyimage/upload"
  # Default search provider image search POST params
  - name: DefaultSearchProviderImageURLPostParams
    type: String
    value: "encoded_image={google:imageThumbnail},image_url={google:imageURL},sbisrc={google:imageSearchSource},original_width={google:imageOriginalWidth},original_height={google:imageOriginalHeight}"
  # Default search provider search URL
  - name: DefaultSearchProviderSearchURL
    type: String
    value: "{google:baseURL}search?q={searchTerms}&{google:RLZ}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:searchClient}{google:sourceId}ie={inputEncoding}"
  # Default search provider suggest URL
  - name: DefaultSearchProviderSuggestURL
    type: String
    value: "{google:baseURL}complete/search?output=chrome&q={searchTerms}"
  # Suggest similar sites whena website can't be found = disabled
  - name: AlternateErrorPagesEnabled
    type: DWord
    value: 0
  # Personalize advertising = disabled
  - name: PersonalizationReportingEnabled
    type: DWord
    value: 0
  - name: SitePerProcess
    type: DWord
    value: 1
- key: HKCU:/Software/Policies/Microsoft/Edge/DefaultSearchProviderEncodings
  entries:
  # Default search provider encodings
  - name: 1
    type: String
    value: UTF-8
# Fake MDM enrollment to allow search provider settings to be used in Edge
- key: HKCU:/Software/Policies/Microsoft/Edge/Recommended
  entries:
  - name: BlockThirdPartyCookies
    type: DWord
    value: 1
- key: HKLM:/SOFTWARE/Microsoft/Enrollments/FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF
  entries:
  - name: EnrollmentState
    type: DWord
    value: 1
  - name: EnrollmentType
    type: DWord
    value: 0
  - name: IsFederated
    type: DWord
    value: 0
- key: HKLM:/SOFTWARE/Microsoft/Provisioning/OMADM/Accounts/FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF
  entries:
  - name: Flags
    type: DWord
    value: 14089087
  - name: AcctUId
    type: String
    value: 0x000000000000000000000000000000000000000000000000000000000000000000000000
  - name: RoamingCount
    type: DWord
    value: 0
  - name: SslClientCertReference
    type: String
    value: MY;User;0000000000000000000000000000000000000000
  - name: ProtoVer
    type: String
    value: 1.2
