---
storeapps:
  # Cortana
- Microsoft.549981C3F5F10
- Microsoft.Messaging
- Microsoft.Microsoft3DViewer
- Microsoft.MicrosoftOfficeHub
- Microsoft.MicrosoftSolitaireCollection
- Microsoft.MicrosoftStickyNotes
- Microsoft.MixedReality.Portal
  # Paint 3D
- Microsoft.MSPaint
  # Mobile Plans
- Microsoft.OneConnect
- Microsoft.People
  # Mail and Calendar
- Microsoft.WindowsCommunicationsApps
- Microsoft.WindowsMaps
  # Voice recorder
- Microsoft.WindowsSoundRecorder
- Microsoft.XboxApp
  # XBox Game Bar
- Microsoft.XboxGamingOverlay
- Microsoft.ZuneMusic
- Microsoft.ZuneVideo
  # Roblox
- RobloxCorporation.Roblox
  # Spotify
- SpotifyAB.SpotifyMusic
